#!/usr/bin/env bash

# Script to generate the index file for the static site
# 
# Looks for changes (modify time) in any of the pages
# and updates the index.md file if needed. This script
# also generates the top text of the index file in the
# updateindex function.



# function to update the index.md file
updateindex() {

echo "<!-- NOTE: This file is autogenerated with gen_index.sh -->" >index.md
echo "" >> index.md
cat resources/index_head.md >> index.md
echo "" >> index.md
# add a link for each of the *.md files to the index.html page
for files in $( ls *.md | sort | grep -v "index.md" ); do
  echo "##### [${files%.*}](${files%.*}.html)" >> index.md
done

}

echo "Checking for additions..."

# index to keep track if something has changed
# if changed is 1 then index.md is updated
CHANGED=0

# if index.md doesnt exist yet, make it 
if [ ! -f index.md ]; then
    touch index.md
    CHANGED=1
fi

# test to see if there are files which are modified after index.md
for files in $( ls *.md); do
  if [ $( stat -c %Y $files ) -gt $( stat -c %Y index.md ) ] ; then
    CHANGED=1
  fi
done

# test to see if this script has changed
if [ $( stat -c %Y resources/gen_index.sh ) -gt $( stat -c %Y index.md ) ] ; then
  CHANGED=1
fi

# test to see if the index_head.md file has changed
if [ $( stat -c %Y resources/index_head.md ) -gt $( stat -c %Y index.md ) ] ; then
  CHANGED=1
fi

# if a file is changed update the index.md file
if [ $CHANGED -eq 1 ] ; then
  updateindex
  echo "Index updated"
else
  echo "No changes"
fi
